require: rubocop-rspec

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*
  TargetRubyVersion: 2.5

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
